version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: db
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6:
